### ISSUE TITLE
ssr connect issue

### ISSUE THREAD

**Issue by xiyuanbao** [noahziheng/ssr-helper#9]
2018-01-25 13:06:55 INFO     util.py:85 loading libsodium from libsodium.so.13
2018-01-25 13:06:55 ERROR    shell.py:50 [Errno 2] No such file or directory: '/var/run/shadowsocksr.pid'
2018-01-25 13:06:55 ERROR    daemon.py:146 not running
IPv6 support
Success!
SSR Python版直连没问题

**Comment by noahziheng** [comment]
Hello xiyunbao,
1.  请提供一下 ssr-helper 的版本和您的发行版信息
2. 请确认 python shadowsocksr 是使用的 manyuser 分支，master 分支内的版本确实有可能出现问题，是上游停止维护的锅

Thanks for feedback,
Noah

**Comment by xiyuanbao** [comment]
你好，
版本为：v1.0.9
发行版：CentOS Linux release 7.4.1708 (Core)
SSR下载使用的指令为：git clone -b manyuser https://github.com/shadowsocksr-backup/shadowsocksr.git
谢谢！

**Comment by noahziheng** [comment]
问题确实很少见，请试一下 `sudo mkdir /var/run`？

**Comment by xiyuanbao** [comment]
我在/var/run下创建了shadowsocksr.pid,ssr connect 不报错：
2018-01-25 22:44:22 INFO     util.py:85 loading libsodium from libsodium.so.13
IPv6 support
stopped
Success!

ssr status和之前一样，
SSR Python Client Status: Running
PID:8146
Current:XXXX（name of my node)
✖ Connection test failed!

将这个pid放进shadowsocksr.pid并没有变化
我还安装了SS-QT5，但是每次启动ssr helper时都将它关闭了，应该没有影响

**Comment by noahziheng** [comment]
一方面查一下配置，这个提示代表 SSR 确实是跑起来了，但是没出大中华局域网，另一方面，试一下 `ssr stop` 后运行 `(你的 SSR 路径)/shadowosocks/local.py -c ~/.config/ssr-helper/default.json`，看一下这种方式能否访问到墙外

**Comment by xiyuanbao** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/.config/ssr-helper/default.json'
我看了下没有创建.config/ssr-helper这个文件夹

**Comment by noahziheng** [comment]
抱歉抱歉，应该是`(你的 SSR 路径)/shadowosocks/local.py -c ~/.config/ssr-helper-nodejs/default.json`

**Comment by xiyuanbao** [comment]
可以正常使用
IPv6 support
2018-01-25 23:38:33 INFO     util.py:85 loading libsodium from /home/sgzzl/anaconda3/lib/libsodium.so.23
2018-01-25 23:38:33 INFO     local.py:50 local start with protocol[auth_aes128_md5] ....
2018-01-25 23:38:33 INFO     local.py:54 starting local at 127.0.0.1:1080
2018-01-25 23:38:33 INFO     asyncdns.py:324 dns server: [('192.168.2.1', 53)]
2018-01-25 23:38:41 INFO     util.py:85 loading libcrypto from .../lib/libcrypto.so.1.0.0

**Comment by noahziheng** [comment]
这就很尴尬了，helper 的原理就是替你执行这句命令...

**Comment by xiyuanbao** [comment]
手动执行过后ssr connect只报ERROR    daemon.py:155 not running这个错误，但切换节点等操作就没用了，重启之后就回到之前的情况了

**Comment by noahziheng** [comment]
感觉是权限或是发行版的问题，还真是没什么思路... 可能是 python 版本的兼容性问题，下一版本正在考虑换到调用 libev 版本

**Comment by xiyuanbao** [comment]
我用sudo试过没啥区别，默认的python版本是3.6.4，是这个的原因吗？

**Comment by LarenDorr** [comment]
我也是一样的报错，后来我更换的另外的ssr，非`shadowsocksr-backup/shadowsocksr`仓库的ssr，然后就..成功了，我也不知道原因。`ssrbackup/shadowsocksr`这个仓库的ssr可用。看了下push时间，不能用的那个是好几年前的，很久没维护了。

**Comment by LarenDorr** [comment]
我又看了下，我是直接clone`shadowsocksr-backup/shadowsocksr`master分支的，没有切换分支。切了之后看了一下应该是最新的可以用，这是我的错误原因。

**Comment by ixingbo** [comment]
我使用deepin  可用,换成centos7之后也是可以正常运行 ,就是ssr status 一直是测试连接失败,用的虚拟机,反反复复恢复快照好多次,都不行,只能运行,测试不能上网,实际上也确实不能上google等互联网.用的[root@localhost ssr]# git clone -b manyuser https://github.com/shadowsocksr-backup/shadowsocksr.git
分支,的问题在哪里呢?请各位帮我解答下,搞了两天,真的是没办法了

**Comment by ixingbo** [comment]
有么有大神给个指导呢?要疯了

**Comment by xiyuanbao** [comment]
试试改用electron-ssr吧

**Comment by ixingbo** [comment]
已经放弃了,都不行....

**Comment by P-DX** [comment]
请问您解决了吗，我遇到了同样的问题。谢谢。

**Comment by jianxuanbing** [comment]
> 我在/var/run下创建了shadowsocksr.pid,ssr connect 不报错：
> 2018-01-25 22:44:22 INFO util.py:85 loading libsodium from libsodium.so.13
> IPv6 support
> stopped
> Success!
> 
> ssr status和之前一样，
> SSR Python Client Status: Running
> PID:8146
> Current:XXXX（name of my node)
> ✖ Connection test failed!
> 
> 将这个pid放进shadowsocksr.pid并没有变化
> 我还安装了SS-QT5，但是每次启动ssr helper时都将它关闭了，应该没有影响

我的一直是
> SSR Python Client Status: Stopped

**Comment by ixingbo** [comment]
libsodium from libsodium.so.13 这个地方的问题还是时间太久了不记得了，请参考我当初笔记 5、安装必要的ssr加密组件 [root@localhost shadowsocksr]# yum update [root@localhost ~]# yum install epel-release -y [root@localhost ~]# yum install libsodium -y 三、centos安装方式: 1、安装yarn [root@localhost ssr]# wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo [root@localhost ssr]# yum install yarn 2、通过yarn 安装ssr-helper [root@localhost ssr]# yarn global add ssr-helper 3、克隆(下载)github上的 ssr(若没有git,请使用yum install git 方式安装git) [root@localhost ssr]# git clone -b manyuser https://github.com/shadowsocksr-backup/shadowsocksr.git 4、将python和ssr客户端建立关联 [root@localhost shadowsocksr]# ssr config /app/ssr/shadowsocksr 5、安装必要的ssr加密组件 [root@localhost shadowsocksr]# yum update [root@localhost ~]# yum install epel-release -y [root@localhost ~]# yum install libsodium -y centos7 暂时不可用     至此：安装完成 Xingbo Yang 邮箱ixingbo8@gmail.com 签名由 网易邮箱大师 定制 On 11/05/2019 19:46, P-DX wrote: 请问您解决了吗，我遇到了同样的问题。谢谢。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
